theme: jekyll-theme-cayman
title: 缘聚今朝 #博客标题
description: 长洲望断水云渺，孤鸿影落化银霓。 #博客描述
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片


gitment:
  enable: true
  githubID: yourid
  repo: yourrepo
  ClientID: 49aad9c5ae5a1a95adee
  ClientSecret: 5f1c714213ca19d4eaf9edc7c7c66fa7a8807b3b
  lazy: true
