theme: jekyll-theme-cayman
title: 法缘 #博客标题
description: 长洲望断水云渺，孤鸿影落化银霓。 #博客描述
keywords: blog,css,html,php #博客关键字

#title hide and show
hide: (つェ⊂)我藏好啦
show: ´∇｀ 呀被发现啦~ 

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "hydrogen.atlinker.cn" # change this to the base hostname & protocol for your site
bulidtime: "1514736000" #博客建立时的时间戳 可进入https://tool.lu/timestamp/将博客建立时的日期转换成时间戳
           #The timestamp at the time of blog establishment can be entered at https://tool.lu/timestamp/to convert the date at the time of blog establishment into a timestamp.

paginate: 8 #同时显示的最大文章数，超过自动分页
paginate_path: "page:num"

background: https://api.dujin.org/bing/1920.php
theme_color: 546E7A

google_analytics:
# hydrogen-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

#install emoji
plugins:
  - jemoji

# social
author: "Link"
image:
twitter:
  username:
#  site:
facebook:
  #publisher: null
  #profile_id: null
  app_id: null
  #authors: null
#  admins:
